name: flutter_payment_gateway_integration
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  awesome_dialog: ^3.1.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_svg: ^2.0.5
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
